[package]
name = "potterscript-example"
version.workspace = true
edition.workspace = true

[dependencies]
potterscript-parser = { path = "../parser" }
potterscript-interpreter = { path = "../interpreter" }


