[package]
name = "potterscript-ron"
version.workspace = true
edition.workspace = true

[dependencies]
potterscript-parser = { "path" = "../parser" }
potterscript-runtime = { "path" = "../runtime" }


